### ISSUE TITLE
Wrong gitRemoteOriginUrl

### ISSUE THREAD

**Issue by Rudyweb** [ALIENQuake/ProjectInfinity#22]
**Check requirements:**
 - OS: 64-bit, fully updated Windows 10
 - .NET Framework version: 4.8
 - Powershell version: 5.1.19041.610

**Upload logs from Logs folder**
[2021.02.06-09꞉35.zip](https://github.com/ALIENQuake/ProjectInfinity/files/5936511/2021.02.06-09.35.zip)

**Describe the bug**
The gitRemoteOriginUrl is the same for all mods : https://github.com/SpellholdStudios/Lucy_the_Wyvern

**Screenshots**
![bug](https://user-images.githubusercontent.com/25640529/107113949-8a38e400-6862-11eb-954e-2198f7d7a153.png)
![bug2](https://user-images.githubusercontent.com/25640529/107113951-8e650180-6862-11eb-9942-c6701e4061c0.png)

**Comment by ALIENQuake** [comment]
@Rudyweb Hi,

You have malformed mods directory structure, you have extracted all mods without extra top-level directory, example:
```
E:\Jeux moddés\Baldur's Gate 2\Mods\BG2SoA
E:\Jeux moddés\Baldur's Gate 2\Mods\Setup-BG2SoA.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\bgtmusic
E:\Jeux moddés\Baldur's Gate 2\Mods\setup-bgtmusic.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\bgttweak
E:\Jeux moddés\Baldur's Gate 2\Mods\setup-bgttweak.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\BoneHillv275
E:\Jeux moddés\Baldur's Gate 2\Mods\Setup-BoneHillv275.tp2
```
so as you can see, all mods share the same 'main' directory. When you mods have such structure, they can be installed just fine but checking for updates and and actually updating the mods is impossible. This is how it should look:
```
E:\Jeux moddés\Baldur's Gate 2\Mods\BG2SoA-main\BG2SoA
E:\Jeux moddés\Baldur's Gate 2\Mods\BG2SoA-main\Setup-BG2SoA.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\bgtmusic-main\bgtmusic
E:\Jeux moddés\Baldur's Gate 2\Mods\bgtmusic-main\setup-bgtmusic.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\bgttweak-main\bgttweak
E:\Jeux moddés\Baldur's Gate 2\Mods\bgttweak-main\setup-bgttweak.tp2
E:\Jeux moddés\Baldur's Gate 2\Mods\BoneHill-main\BoneHillv275
E:\Jeux moddés\Baldur's Gate 2\Mods\BoneHill-main\Setup-BoneHillv275.tp2
```

The reason why you getting the error message is because you have updated Lucy_the_Wyvern mod as a first one, then PI created `E:\Jeux moddés\Baldur's Gate 2\Mods\.git` directory and put the delta updates for this mod there. But because `E:\Jeux moddés\Baldur's Gate 2\Mods\` is shared across all other mods, PI now thinks that there is a mismatch between ini Download link' and local updates dir.

1. Remove `E:\Jeux moddés\Baldur's Gate 2\Mods\.git` directory (it's hidden)
2. Extract all mods again, this time every mod should have extra top-level directory

Let me know if you need more assistance.

**Comment by Rudyweb** [comment]
Thank you for your detailed explanations!
I wouldn't need any help, I understand the problem perfectly now.

I had kept the same folder structure used with BWP.

**Comment by ALIENQuake** [comment]
@Rudyweb No problem. BTW: you have a lot of outdated mod versions, please update all which you can. Look at G3/SHS/PPG websites/github.com.

**Comment by Rudyweb** [comment]
The mods are up to date, but for some reason, all *.tp2 files have an extra empty line at the end of the file.
Maybe because I use a manually downloaded version on their Github ?

**Comment by ALIENQuake** [comment]
It shouldn't matter at all.
